logging:
  file: 
    name: application.log
  level:
    root: INFO
    
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      schema: test
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/postgres
    #url: jdbc:postgresql://${DB_HOST:localhost}/postgres
    username: postgres
    password: 'root'

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    
server:
  port: 8002